export const BADGES = [
  {
    id: 'first_task',
    label: 'Premier Pas',
    desc: 'Complète ta 1ère tâche',
    emoji: '👣',
    check: (p) => p.totalTasksDone >= 1,
  },
  {
    id: 'first_routine',
    label: 'Héros du Matin',
    desc: 'Termine une routine complète',
    emoji: '☀️',
    check: (p) => p.totalRoutinesDone >= 1,
  },
  {
    id: 'streak_3',
    label: 'Flamme x3',
    desc: '3 jours de suite',
    emoji: '🔥',
    check: (p) => p.streak >= 3,
  },
  {
    id: 'streak_7',
    label: 'Flamme x7',
    desc: '7 jours de suite',
    emoji: '🔥🔥',
    check: (p) => p.streak >= 7,
  },
  {
    id: 'streak_30',
    label: 'Légende',
    desc: '30 jours de suite',
    emoji: '🏆',
    check: (p) => p.streak >= 30,
  },
  {
    id: 'tasks_10',
    label: 'Apprenti',
    desc: '10 tâches accomplies',
    emoji: '⚡',
    check: (p) => p.totalTasksDone >= 10,
  },
  {
    id: 'tasks_50',
    label: 'Expert',
    desc: '50 tâches accomplies',
    emoji: '💪',
    check: (p) => p.totalTasksDone >= 50,
  },
  {
    id: 'tasks_100',
    label: 'Maître',
    desc: '100 tâches accomplies',
    emoji: '👑',
    check: (p) => p.totalTasksDone >= 100,
  },
  {
    id: 'level_5',
    label: 'Guerrier',
    desc: 'Atteins le niveau 5',
    emoji: '⚔️',
    check: (p) => p.level >= 5,
  },
  {
    id: 'level_10',
    label: 'Champion',
    desc: 'Atteins le niveau 10',
    emoji: '🛡️',
    check: (p) => p.level >= 10,
  },
  {
    id: 'coins_100',
    label: 'Économe',
    desc: 'Gagne 100 pièces',
    emoji: '💰',
    check: (p) => p.totalCoinsEarned >= 100,
  },
  {
    id: 'coins_500',
    label: 'Riche !',
    desc: 'Gagne 500 pièces au total',
    emoji: '💎',
    check: (p) => p.totalCoinsEarned >= 500,
  },
  {
    id: 'first_purchase',
    label: 'Acheteur',
    desc: 'Achète ton 1er accessoire',
    emoji: '🛍️',
    check: (p) => p.unlockedItems.length >= 1,
  },
  {
    id: 'routines_10',
    label: 'Régulier',
    desc: '10 routines complètes',
    emoji: '🎯',
    check: (p) => p.totalRoutinesDone >= 10,
  },
  {
    id: 'perfect_week',
    label: 'Semaine Parfaite',
    desc: '7 jours sans rien manquer',
    emoji: '🌟',
    check: (p) => p.streak >= 7 && p.totalRoutinesDone >= 7,
  },
];

export const getBadgeById = (id) => BADGES.find((b) => b.id === id);
